package model.rovo;

import java.math.BigDecimal;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 23 16:45:14 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DummySubRateROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EmployeeId,
        EmployeeName,
        EmployeeNumber,
        Rate,
        Ot1Rate,
        Ot2Rate,
        NoOfDays,
        TotalIncentivehours,
        TotalOvertimehours,
        Bill,
        NetAmount,
        BU_ID,
        EmployeesROVO,
        Subcont_Rate_Hdr_VO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int EMPLOYEENAME = AttributesEnum.EmployeeName.index();
    public static final int EMPLOYEENUMBER = AttributesEnum.EmployeeNumber.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int OT1RATE = AttributesEnum.Ot1Rate.index();
    public static final int OT2RATE = AttributesEnum.Ot2Rate.index();
    public static final int NOOFDAYS = AttributesEnum.NoOfDays.index();
    public static final int TOTALINCENTIVEHOURS = AttributesEnum.TotalIncentivehours.index();
    public static final int TOTALOVERTIMEHOURS = AttributesEnum.TotalOvertimehours.index();
    public static final int BILL = AttributesEnum.Bill.index();
    public static final int NETAMOUNT = AttributesEnum.NetAmount.index();
    public static final int BU_ID = AttributesEnum.BU_ID.index();
    public static final int EMPLOYEESROVO = AttributesEnum.EmployeesROVO.index();
    public static final int SUBCONT_RATE_HDR_VO1 = AttributesEnum.Subcont_Rate_Hdr_VO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DummySubRateROVORowImpl() {
    }
}

