package model.vo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 19 20:22:15 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Subcont_Rate_Hdr_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Subcont_Rate_Hdr_VOImpl() {
    }

    /**
     * Returns the variable value for BV_Id.
     * @return variable value for BV_Id
     */
    public BigDecimal getBV_Id() {
        return (BigDecimal) ensureVariableManager().getVariableValue("BV_Id");
    }

    /**
     * Sets <code>value</code> for variable BV_Id.
     * @param value value to bind as BV_Id
     */
    public void setBV_Id(BigDecimal value) {
        ensureVariableManager().setVariableValue("BV_Id", value);
    }

    /**
     * Returns the bind variable value for BV_USER_NAME.
     * @return bind variable value for BV_USER_NAME
     */
    public String getBV_USER_NAME() {
        return (String) getNamedWhereClauseParam("BV_USER_NAME");
    }

    /**
     * Sets <code>value</code> for bind variable BV_USER_NAME.
     * @param value value to bind as BV_USER_NAME
     */
    public void setBV_USER_NAME(String value) {
        setNamedWhereClauseParam("BV_USER_NAME", value);
    }

    /**
     * Returns the variable value for p_Id.
     * @return variable value for p_Id
     */
    public BigDecimal getp_Id() {
        return (BigDecimal) ensureVariableManager().getVariableValue("p_Id");
    }

    /**
     * Sets <code>value</code> for variable p_Id.
     * @param value value to bind as p_Id
     */
    public void setp_Id(BigDecimal value) {
        ensureVariableManager().setVariableValue("p_Id", value);
    }
}

