package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 19 20:22:15 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Subcont_Rate_Hdr_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_SUBCON_RATE_HDR_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BusinessUnitId,
        BusinessUnitName,
        CreatedBy,
        CreationDate,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        PeriodName,
        Status,
        SubconRateHdrId,
        ProjectId,
        ProjectName,
        ProjectNumber,
        Subcont_Rate_Dtl_VO,
        BusinessUnit_ROVO,
        Period_ROVO,
        ProjectRoVo1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int BUSINESSUNITNAME = AttributesEnum.BusinessUnitName.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int PERIODNAME = AttributesEnum.PeriodName.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int SUBCONRATEHDRID = AttributesEnum.SubconRateHdrId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int PROJECTNAME = AttributesEnum.ProjectName.index();
    public static final int PROJECTNUMBER = AttributesEnum.ProjectNumber.index();
    public static final int SUBCONT_RATE_DTL_VO = AttributesEnum.Subcont_Rate_Dtl_VO.index();
    public static final int BUSINESSUNIT_ROVO = AttributesEnum.BusinessUnit_ROVO.index();
    public static final int PERIOD_ROVO = AttributesEnum.Period_ROVO.index();
    public static final int PROJECTROVO1 = AttributesEnum.ProjectRoVo1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Subcont_Rate_Hdr_VORowImpl() {
    }
}

