package model.rovo;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 26 15:00:55 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DummyJobTypeROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EmployeeId,
        EmployeeName,
        EmployeeNumber,
        JobTyperate,
        Startdate,
        ActiveFlag,
        Overtimerate,
        Incentiverate,
        BU_ID,
        EmployeesROVO,
        JobType_Hdr_VO,
        GetEmployeeDtls_RoVo;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int EMPLOYEENAME = AttributesEnum.EmployeeName.index();
    public static final int EMPLOYEENUMBER = AttributesEnum.EmployeeNumber.index();
    public static final int JOBTYPERATE = AttributesEnum.JobTyperate.index();
    public static final int STARTDATE = AttributesEnum.Startdate.index();
    public static final int ACTIVEFLAG = AttributesEnum.ActiveFlag.index();
    public static final int OVERTIMERATE = AttributesEnum.Overtimerate.index();
    public static final int INCENTIVERATE = AttributesEnum.Incentiverate.index();
    public static final int BU_ID = AttributesEnum.BU_ID.index();
    public static final int EMPLOYEESROVO = AttributesEnum.EmployeesROVO.index();
    public static final int JOBTYPE_HDR_VO = AttributesEnum.JobType_Hdr_VO.index();
    public static final int GETEMPLOYEEDTLS_ROVO = AttributesEnum.GetEmployeeDtls_RoVo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DummyJobTypeROVORowImpl() {
    }
}

