package model.rovo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 19 16:11:13 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Xxstg_JobDtls_RoVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Xxstg_JobDtls_RoVoImpl() {
    }
}

