package model.rovo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 23 00:16:43 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobDateValidation_ROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public JobDateValidation_ROVOImpl() {
    }
}

