package model.am;

import java.sql.CallableStatement;

import java.sql.SQLException;

import java.util.ArrayList;

import model.rovo.DummyJobTypeROVOImpl;
import model.rovo.DummySubRateROVOImpl;
import model.rovo.JobDateValidation_ROVOImpl;

import model.vo.Subcont_Rate_Hdr_VOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 24 18:51:25 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Naresco_AMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Naresco_AMImpl() {
    }

    /**
     * Container's getter for Subcont_Rate_Hdr_VO.
     * @return Subcont_Rate_Hdr_VO
     */
    public Subcont_Rate_Hdr_VOImpl getSubcont_Rate_Hdr_VO() {
        return (Subcont_Rate_Hdr_VOImpl) findViewObject("Subcont_Rate_Hdr_VO");
    }

    /**
     * Container's getter for Subcont_Rate_Dtl_VO.
     * @return Subcont_Rate_Dtl_VO
     */
    public ViewObjectImpl getSubcont_Rate_Dtl_VO() {
        return (ViewObjectImpl) findViewObject("Subcont_Rate_Dtl_VO");
    }

    /**
     * Container's getter for JobType_Hdr_VO.
     * @return JobType_Hdr_VO
     */
    public ViewObjectImpl getJobType_Hdr_VO() {
        return (ViewObjectImpl) findViewObject("JobType_Hdr_VO");
    }

    /**
     * Container's getter for JobType_Dtl_VO.
     * @return JobType_Dtl_VO
     */
    public ViewObjectImpl getJobType_Dtl_VO() {
        return (ViewObjectImpl) findViewObject("JobType_Dtl_VO");
    }

    /**
     * Container's getter for DummySubRateROVO.
     * @return DummySubRateROVO
     */
    public DummySubRateROVOImpl getDummySubRateROVO() {
        return (DummySubRateROVOImpl) findViewObject("DummySubRateROVO");
    }

    /**
     * Container's getter for DummyJobTypeROVO.
     * @return DummyJobTypeROVO
     */
    public DummyJobTypeROVOImpl getDummyJobTypeROVO() {
        return (DummyJobTypeROVOImpl) findViewObject("DummyJobTypeROVO");
    }

    /**
     * Container's getter for JobType_Dtl_VO1.
     * @return JobType_Dtl_VO1
     */
    public ViewObjectImpl getJobType_Dtl_VO1() {
        return (ViewObjectImpl) findViewObject("JobType_Dtl_VO1");
    }

    /**
     * Container's getter for JobDateValidation_ROVO.
     * @return JobDateValidation_ROVO
     */
    public JobDateValidation_ROVOImpl getJobDateValidation_ROVO() {
        return (JobDateValidation_ROVOImpl) findViewObject("JobDateValidation_ROVO");
    }

    /**
     * Container's getter for SubcontHdrLine_VL.
     * @return SubcontHdrLine_VL
     */
    public ViewLinkImpl getSubcontHdrLine_VL() {
        return (ViewLinkImpl) findViewLink("SubcontHdrLine_VL");
    }

    /**
     * Container's getter for JobTypeHdrLine_VL.
     * @return JobTypeHdrLine_VL
     */
    public ViewLinkImpl getJobTypeHdrLine_VL() {
        return (ViewLinkImpl) findViewLink("JobTypeHdrLine_VL");
    }

    /**
     * Container's getter for JobTypeHdrLine_VL1.
     * @return JobTypeHdrLine_VL1
     */
    public ViewLinkImpl getJobTypeHdrLine_VL1() {
        return (ViewLinkImpl) findViewLink("JobTypeHdrLine_VL1");
    }
//    public Number countJobTypeValFunc(int empNo, String date, int  job_hdr_id) {
//          
//
//    
//
//
//           try {
//              
//
//    
//
//               
//
//    
//
//              
//
//    
//
//               // Calling Package
//               CallableStatement cs =
//                   this.getDBTransaction()
//                   .createCallableStatement("{call JOBDATEVALIDATION (?,?,?)}");
//
//    
//
//               // Setting In parameter
//               cs.setInt(1, empNo);
//               cs.setString(2, date);
//               cs.setInt(3, job_hdr_id);
//    
//
//           
// 
//
//    
//
//           } catch (Exception e) {
//               e.printStackTrace();
//           }
//          
//       }
//     public String areaChangeApproval(Number empNo,  Number  job_hdr_id,String date){
//        String p_errorMessgae = null;
//        try {
////            Number p_emp_no = new Number(empNo);
//            
//            String stmt1 = "begin :v_Return := JOBDATEVALIDATION(:empNo,:job_hdr_id,:date); end;";
//            CallableStatement cst = null;
//                cst = this.getDBTransaction().createCallableStatement(stmt1, 0);
//                cst.setObject("p_area_change_id", p_areachangeHdrId);
//            
//            
//                cst.executeUpdate();
//                if (cst.getObject("p_err_msg") != null) {
//                    p_errorMessgae = cst.getObject("p_err_msg").toString();
//                }
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
//        return p_errorMessgae;
//    }
//

    /**
     * Container's getter for JobTypHdrDtl_RoVo1.
     * @return JobTypHdrDtl_RoVo1
     */
    public ViewObjectImpl getJobTypHdrDtl_RoVo1() {
        return (ViewObjectImpl) findViewObject("JobTypHdrDtl_RoVo1");
    }
}

