package model.rovo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 23 16:45:14 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DummySubRateROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DummySubRateROVOImpl() {
    }
}

